#include "main.h"

spelli bsmeta<spelli>::elements[] = {{0, "Волшебная броня", "волшебной брони", 10, {Creature}},
{0, "Благословение", "благословения", 6, {Creature, {NotYou, Friends, AllTargets}, Reach}, {1, 3}},
{0, "Зачаровать предмет", "зачарования предмета", 30, {Item, {AlwaysChoose}, You, "Какой предмет сделать волшебным?"}},
{0, "Поговорить с персоной", "разговора", 0, {Creature, {NotYou}, Close, "С кем вы хотите поговорить?"}},
{0, "Очаровать персону", "шарма", 20, {Creature, {NotYou, Enemies, RandomTargets}, Near, "Кто станет вашим другом?"}},
{0, "Обнаружить зло", "обнаружения зла", 10, {Item, {RandomTargets}}},
{0, "Обнаружить волшебство", "обнаружения магии", 10, {Item, {RandomTargets}}},
{0, "Страх", "страха", 10, {Creature, {Enemies, TwoTargets}, Near}},
{2, "Исцеление", "исцеления", 4, {Creature, {Friends}, Reach, "Кому вылечить ранения?"}, {1, 6}, 2},
{0, "Опознание", "опознания", 20, {Item, {AlwaysChoose}, You, "Какой предмет хотите опознать?"}},
{0, "Невидимость", "невидимости", 8, {Creature, {}, You}},
{0, "Открытие дверей", "открытия дверей", 1, {Object, {AllTargets}, Near}},
{0, "Свет", "света", 1, {Creature, {Friends}, Near, "Где появится свет?"}},
{0, "Волшебный заряд", "волшебного заряда", 3, {Creature, {Enemies}, Near}, {1, 4}, 1, Magic, "вылетел светящийся шарик, поразивший цель"},
{0, "Отравление", "яда", 2, {Creature, {Enemies}, Close}},
{0, "Починка", "починки", 2, {Item, {}, You, "Какой предмет починить?"}},
{0, "Убрать яд", "яда", 10, {Creature, {Friends}, Close, "У кого убрать яд?"}},
{0, "Убрать болезнь", "болезни", 20, {Creature, {Friends}, Close, "Кого излечить от болезни?"}},
{0, "Болезнь", "болезни", 10, {Creature, {Enemies}, Close, "Кого заразить?"}},
{0, "Волшебный щит", "щита", 6, {Creature, {Friends}, Close, "На кого наложить щит?"}},
{0, "Шокирующая хватка", "электричества", 3, {Creature, {Enemies}, Close}, {1, 8}, 2, Electricity, "сорвался элекрический заряд"},
{0, "Сон", "сна", 10, {Creature, {Enemies, TwoTargets, NotYou}, Reach}},
{0, "Замедлить монстра", "замедления", 12, {Creature, {Enemies, RandomTargets}, Near}},
{0, "Паутина", "паутины", 10, {Creature, {Enemies}, Near}},
};
assert_enum(spell, LastSpell);