#include "main.h"

spelli bsmeta<spelli>::elements[] = {{"Волшебная броня", "волшебной брони", 10, {Creature}},
{"Благословение", "благословения", 6, {Creature, {NotYou, Friends, AllTargets}, Reach}, {1, 3}},
{"Зачаровать предмет", "зачарования предмета", 30, {Item, {AlwaysChoose}, You, "Какой предмет сделать волшебным?"}},
{"Очаровать персону", "шарма", 20, {Creature, {NotYou, Enemies, RandomTargets}, Near, "Кто станет вашим другом?"}},
{"Обнаружить зло", "обнаружения зла", 10, {Item, {RandomTargets}}},
{"Обнаружить волшебство", "обнаружения магии", 10, {Item, {RandomTargets}}},
{"Страх", "страха", 10, {Creature, {Enemies, TwoTargets}, Near}},
{"Исцеление", "исцеления", 4, {Creature, {Friends}, Reach, "Кому вылечить ранения?"}, {1, 6}, 2},
{"Опознание", "опознания", 20, {Item, {AlwaysChoose}, You, "Какой предмет хотите опознать?"}},
{"Невидимость", "невидимости", 8, {Creature, {}, You}},
{"Свет", "света", 1, {Creature, {Friends}, Near, "Где появится свет?"}},
{"Волшебный заряд", "волшебного заряда", 2, {Creature, {Enemies}, Near}, {1, 4}, 1, Magic, "вылетел светящийся шарик, поразивший цель"},
{"Отравление", "яда", 2, {Creature, {Enemies}, Close}},
{"Починка", "починки", 2, {Item, {}, You, "Какой предмет починить?"}},
{"Убрать яд", "яда", 10, {Creature, {Friends}, Close, "У кого убрать яд?"}},
{"Убрать болезнь", "болезни", 20, {Creature, {Friends}, Close, "Кого излечить от болезни?"}},
{"Болезнь", "болезни", 10, {Creature, {Enemies}, Close, "Кого заразить?"}},
{"Волшебный щит", "щита", 6, {Creature, {Friends}, Close, "На кого наложить щит?"}},
{"Шокирующая хватка", "электричества", 3, {Creature, {Enemies}, Close}, {1, 8}, 2, Electricity, "сорвался элекрический заряд"},
{"Сон", "сна", 10, {Creature, {Enemies, TwoTargets, NotYou}, Reach}},
{"Замедлить монстра", "замедления", 12, {Creature, {Enemies, RandomTargets}, Near}},
};
assert_enum(spell, SlowMonster);