#include "main.h"

//Plain, Water, Floor, Wall, Road,
//Swamp, Hill,
//Sea, Foothills, Mountains, CloudPeaks, Forest,
//City,
tilei bsmeta<tilei>::elements[] = {{"Plain", "Равнина"},
{"Water", "Вода"},
{"Floor", "Пол"},
{"Wall", "Стена"},
{"Road", "Дорога"},
{"Swamp", "Болото"},
{"Hill", "Холм"},
{"Sea", "Море"},
{"Foothills", "Подгорье"},
{"Mountains", "Горы"},
{"CloudPeaks", "Туманные пики"},
{"Forest", "Лес"},
{"City", "Город"},
};